# Generated by Django 6.0.3 on 2026-03-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=255),
        ),
    ]
