# Generated by Django 6.0.3 on 2026-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=4),
        ),
    ]
